### ISSUE TITLE
Fix the OBJ Importer

### ISSUE THREAD

**Issue by William-McGonagle** [William-McGonagle/sledge#4]
We are currently experiencing issues with the OBJ importer in our project. The importer is not correctly indexing the triangles in the imported mesh, which is causing incorrect rendering in our application.

To fix this issue, we need to investigate the cause of the indexing problem and update the importer code accordingly.

Todo:
- [ ] Investigate the cause of the indexing problem in the OBJ importer.
- [ ] Update the importer code to correctly index the triangles in the imported mesh.
- [ ] Test the updated importer code to ensure that it is working correctly.
- [ ] Ensure that the updated code is well-documented and adheres to the project's coding standards.

**Comment by chseasn** [comment]
Hello! I am a student in computer science and new to contributing to open-source projects. I was hoping that this is an issue I can help with. Where can I get started?

**Comment by William-McGonagle** [comment]
Hey @chseasn 

You can start by running `dotnet run` on the project, and uncomment out the code that says Mesh3D.FromObj. That's the function that's causing the problem because there must be some sort of indexing problem. I'm not sure what the issue is exactly but if you want to check it out, I'll assign you to the issue. 

Cheers,
William McGonagle

**Comment by chseasn** [comment]
Sounds good I will give it a shot!

**Comment by chseasn** [comment]
I'm not sure whether I see a function called FromObj in Mesh3D.cs. Am I searching in the wrong place? I noticed some commented out code in scene3D and UIRenderer as well.

**Comment by William-McGonagle** [comment]
Oh– Sorry! It's a static function called `Mesh3D.LoadObj`.

**Comment by chseasn** [comment]
I would like to create a pull request with some changes I made in `Mesh3D.LoadObj` When I run 'git push origin master' it says that access has been denied. I have tried creating my own SSH key and using Git through that, but unfortunately that does not work as well. 
![image](https://user-images.githubusercontent.com/122842728/233624871-e6b65c31-1eb1-464b-8fbd-c69d4115e736.png)

**Comment by William-McGonagle** [comment]
Fixed with #12
