### ISSUE TITLE
Add Documentation to the `InputManager` Class

### ISSUE THREAD

**Issue by William-McGonagle** [William-McGonagle/sledge#7]
The `InputManager` class is a critical component of our project's input system, which handles user input from various sources. However, the class is currently lacking in documentation, which makes it difficult for new developers to understand how to use it effectively.

To improve the usability of the `InputManager` class, we need to add comprehensive documentation that describes the class's purpose, methods, and properties. This will make it easier for developers to understand how to use the class and will reduce the likelihood of bugs and errors in the codebase.

Todo
- [ ] Review the existing `InputManager` class code and identify its purpose, methods, and properties.
- [ ] Write comprehensive documentation that describes the class's purpose, methods, and properties.
- [ ] Ensure that the documentation is easy to understand and provides examples of how to use the class effectively.
- [ ] Add the documentation to the class file and ensure that it is up-to-date with any changes to the class.

**Comment by SrAndros** [comment]
I can take care of documenting this file.

**Comment by SrAndros** [comment]
Added PR #11 adding basic documentation.
